trigger:
  - main

pr:
  - main

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: docker build -t azure-pipelines-test-container .
    displayName: Build Container
  - script: docker history azure-pipelines-test-container
    displayName: Show History
